# Generated by Django 2.2 on 2019-10-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_adduser_cpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adduser',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='adduser',
            name='Username',
        ),
    ]
